include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_redundant_argument_values: true
    depend_on_referenced_packages: false
    library_private_types_in_public_api: false
    use_build_context_synchronously: false
    prefer_relative_imports: true
    avoid_print: false

analyzer:
  errors:
    unused_element: ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
